### PR TITLE
Add postinstall hooks for webpack config copy

### PR DESCRIPTION
**Pull request by vjoao**

### CODE REVIEW

**Comment by tralves** [comment]
Thanks for the PR! It is nice to see people contributing to this project.

I do have a couple of questions:

1. `fs.createWriteStream(__dirname + '\\..\\..\\' + 'webpack.config.js')` seems to be platform dependent, namely for windows. Can we change to use node's `path` api?

2. are you sure that the file will be copied 2 levels up? Should be only one level, doesn't it?

Meanwhile, I will try to figure these things out too.

**Comment by vjoao** [comment]
Should be 2 levels because it's inside the node_modules folder after install, isn't it?
Uptated PR

**Comment by tralves** [comment]
Not really. The content of the template will be under `app`. That's why the README.md says `mv app/webpack.config.js .`.

Also, you can test the changes on the template without pulling it. You could test it from your fork with:
```
tns create hello-ns-vue --template https://github.com/vjoao/nativescript-vue-webpack-template
```
or, even better, test it from your local folder:
```
tns create hello-ns-vue --template ./nativescript-vue-webpack-template
```

**Comment by tralves** [comment]
Oh! I just found out that you were right! 

And I am too :) The template ends up being a dependency, AND the content goes to `./app`.

**Comment by tralves** [comment]
You were right, it executes from `node_modules`. `tns` does some magic I was not aware.

I made a little change to move the file instead of copying it so it doesn't end repeated in two places.

Thanks for the PR!

**Pull request merged**
